version: "3"

services:
  ruby:
    build:
      context: .
      dockerfile: .deploy/Dockerfile
    volumes:
      - .:/app
    environment:
      RAILS_ENV: ${RAILS_ENV}
      RAILS_PG_DB: ${RAILS_PG_DB}
      RAILS_PG_HOST: ${RAILS_PG_HOST}
      RAILS_PG_USER: ${RAILS_PG_USER}
      RAILS_PG_PASS: ${RAILS_PG_PASS}
      RAILS_MAX_THREADS: ${RAILS_MAX_THREADS}
    tty: true
    stdin_open: true

  nginx:
    build:
      context: .
      dockerfile: .deploy/nginx.Dockerfile
    ports:
      - ${DOCKER_NGINX_PORT}:80
    volumes:
      - .:/app

  postgres:
    image: postgres:${DOCKER_PG_VERSION}
    environment:
      POSTGRES_PASSWORD: ${DOCKER_PG_PASS}
      POSTGRES_DB: ${DOCKER_PG_DB}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - ${DOCKER_PG_PORT}:5432

volumes:
  db: